package com.tuapp.eventos.data.repository

import com.tuapp.eventos.di.SupabaseModule
import com.tuapp.eventos.domain.model.Event
import com.tuapp.eventos.domain.model.EventMember
import com.tuapp.eventos.domain.model.EventRoleMember
import com.tuapp.eventos.domain.model.Expense
import com.tuapp.eventos.domain.model.Role
import com.tuapp.eventos.domain.model.GroupMember
import com.tuapp.eventos.domain.model.MemberRole
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Columns
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

class EventRepositoryImpl : EventRepository {
    
    private val client = SupabaseModule.client

    override fun getEvents(): Flow<List<Event>> = flow {
        try {
            val events = client.from("events")
                .select()
                .decodeList<Event>()
            emit(events)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching events: ${e.message}")
            emit(emptyList())
        }
    }

    override suspend fun getEventById(id: String): Event? {
        return try {
            client.from("events")
                .select {
                    filter {
                        eq("id", id)
                    }
                }
                .decodeSingle<Event>()
        } catch (e: Exception) {
            null
        }
    }

    override suspend fun createEvent(event: Event, roles: List<Role>): Result<String> {
        return try {
            android.util.Log.d("EventRepository", "Creating event: $event")
            
            // Convert to JSON and remove fields that should be generated by DB
            val eventJson = Json.encodeToJsonElement(Event.serializer(), event).jsonObject.toMutableMap()
            eventJson.remove("id")
            eventJson.remove("created_at")
            eventJson.remove("updated_at")
            
            // Filter out any remaining nulls to avoid constraint violations
            val filteredJson = eventJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
            
            val insertedEvent = client.from("events")
                .insert(filteredJson) {
                    select()
                }
                .decodeSingle<Event>()
            
            val eventId = insertedEvent.id ?: throw Exception("Failed to get event ID")

            if (roles.isNotEmpty()) {
                val rolesToInsert = roles.map { role ->
                    val roleJson = Json.encodeToJsonElement(Role.serializer(), role.copy(eventId = eventId)).jsonObject.toMutableMap()
                    roleJson.remove("id")
                    roleJson.remove("created_at")
                    roleJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
                }
                client.from("event_roles").insert(rolesToInsert)
            }

            val ownerMember = EventMember(
                eventId = eventId,
                userId = event.createdBy,
                isAdmin = true,
                status = "active"
            )
            
            // Clean member JSON as well
            val ownerJson = Json.encodeToJsonElement(EventMember.serializer(), ownerMember).jsonObject.toMutableMap()
            ownerJson.remove("joined_at")
            ownerJson.remove("created_at")
            
            client.from("event_members").insert(ownerJson.filterValues { it !is kotlinx.serialization.json.JsonNull })

            Result.success(eventId)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error creating event: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun updateEvent(event: Event): Result<Unit> {
        return try {
            client.from("events").update(event) {
                filter {
                    eq("id", event.id ?: "")
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error updating event: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun joinEvent(eventId: String, userId: String): Result<Unit> {
        return try {
            android.util.Log.d("EventRepository", "Attempting to join event $eventId for user $userId")
            // First check if already member to avoid duplicate key error
            val existing = client.from("event_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                        eq("user_id", userId)
                    }
                }.decodeSingleOrNull<EventMember>()

            if (existing != null) {
                android.util.Log.d("EventRepository", "User already joined event")
                return Result.success(Unit)
            }

            val member = EventMember(
                eventId = eventId,
                userId = userId,
                isAdmin = false,
                status = "active"
            )
            
            // Clean member JSON to avoid null date constraint errors
            val memberJson = Json.encodeToJsonElement(EventMember.serializer(), member).jsonObject.toMutableMap()
            memberJson.remove("joined_at")
            memberJson.remove("created_at")
            
            client.from("event_members").insert(memberJson.filterValues { it !is kotlinx.serialization.json.JsonNull })

            android.util.Log.d("EventRepository", "Successfully joined event")
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error joining event: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun leaveEvent(eventId: String, userId: String): Result<Unit> {
        return try {
            client.from("event_members").delete {
                filter {
                    eq("event_id", eventId)
                    eq("user_id", userId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error leaving event: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun getParticipatingEventIds(userId: String): Result<List<String>> {
        return try {
            val members = client.from("event_members")
                .select {
                    filter {
                        eq("user_id", userId)
                    }
                }
                .decodeList<EventMember>()
            Result.success(members.map { it.eventId })
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun isUserParticipating(eventId: String, userId: String): Result<Boolean> {
        return try {
            val member = client.from("event_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                        eq("user_id", userId)
                    }
                }
                .decodeSingleOrNull<EventMember>()
            Result.success(member != null)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getEventParticipants(eventId: String): Result<List<GroupMember>> {
        return try {
            val response = client.from("event_members")
                .select(Columns.raw("*, profiles(*)")) {
                    filter {
                        eq("event_id", eventId)
                    }
                }
            
            val jsonArray = Json.parseToJsonElement(response.data).jsonArray
            
            val participants = jsonArray.map { element ->
                val obj = element.jsonObject
                val userId = obj["user_id"]?.jsonPrimitive?.content ?: ""
                val isAdmin = obj["is_admin"]?.jsonPrimitive?.boolean ?: false
                
                val profileObj = obj["profiles"]?.jsonObject
                val fullName = profileObj?.get("full_name")?.jsonPrimitive?.content ?: "Usuario"
                val username = profileObj?.get("username")?.jsonPrimitive?.content ?: "usuario"
                
                GroupMember(
                    userId = userId,
                    userName = fullName,
                    role = if (isAdmin) MemberRole.ADMIN else MemberRole.MEMBER,
                    email = "@$username"
                )
            }
            
            Result.success(participants)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error getting participants: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun getRoles(eventId: String): Result<List<Role>> {
        return try {
            val roles = client.from("event_roles")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<Role>()
            Result.success(roles)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun createRole(role: Role): Result<Unit> {
        return try {
            val roleJson = Json.encodeToJsonElement(Role.serializer(), role).jsonObject.toMutableMap()
            roleJson.remove("id")
            roleJson.remove("created_at")
            
            val filteredJson = roleJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
            
            client.from("event_roles").insert(filteredJson)
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error creating role: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun updateRole(role: Role): Result<Unit> {
        return try {
            client.from("event_roles").update(role) {
                filter {
                    eq("id", role.id ?: "")
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteRole(roleId: String): Result<Unit> {
        return try {
            client.from("event_roles").delete {
                filter {
                    eq("id", roleId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun assignRoleToUser(roleId: String, userId: String, eventId: String): Result<Unit> {
        return try {
            // Check if user is participating in the event first
            val isParticipating = isUserParticipating(eventId, userId).getOrDefault(false)
            if (!isParticipating) {
                return Result.failure(Exception("Debes unirte al evento antes de asignarte un rol"))
            }

            val roleMember = EventRoleMember(
                roleId = roleId,
                userId = userId,
                eventId = eventId
            )
            client.from("event_role_members").insert(roleMember)
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error assigning role: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun removeRoleFromUser(roleId: String, userId: String): Result<Unit> {
        return try {
            client.from("event_role_members").delete {
                filter {
                    eq("role_id", roleId)
                    eq("user_id", userId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getRoleMembers(eventId: String): Result<List<EventRoleMember>> {
        return try {
            val members = client.from("event_role_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<EventRoleMember>()
            Result.success(members)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun updateEventStatus(eventId: String, status: String): Result<Unit> {
        return try {
            client.from("events").update(mapOf("status" to status)) {
                filter { eq("id", eventId) }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun assignMultipleRoles(assignments: List<EventRoleMember>): Result<Unit> {
        return try {
            client.from("event_role_members").insert(assignments)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteEvent(eventId: String): Result<Unit> {
        return try {
            client.from("events").delete {
                filter {
                    eq("id", eventId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error deleting event: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun addExpense(eventId: String, expense: Expense): Result<Unit> {
        return try {
            // Log for debugging
            android.util.Log.d("EventRepository", "Preparing to save expense: $expense")
            
            val expenseJson = Json.encodeToJsonElement(Expense.serializer(), expense).jsonObject.toMutableMap()
            expenseJson.remove("id") // Always let DB generate UUID
            
            // If date is null in object, remove it from JSON so DB uses DEFAULT now()
            if (expense.date == null) {
                expenseJson.remove("date")
            }
            
            val filteredJson = expenseJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
            
            client.from("expenses").insert(filteredJson)
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Failed to add expense: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun getExpenses(eventId: String): List<Expense> {
        return try {
            client.from("expenses")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<Expense>()
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching expenses: ${e.message}")
            emptyList()
        }
    }

    override suspend fun getTasks(eventId: String): List<com.tuapp.eventos.domain.model.EventTask> {
        return try {
            client.from("event_tasks")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<com.tuapp.eventos.domain.model.EventTask>()
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching tasks: ${e.message}")
            emptyList()
        }
    }

    override fun getEventsByGroup(groupId: String): Flow<List<Event>> = flow {
        try {
            val events = client.from("events")
                .select {
                    filter {
                        eq("group_id", groupId)
                    }
                }
                .decodeList<Event>()
            emit(events)
        } catch (e: Exception) {
            emit(emptyList())
        }
    }
}
