package com.tuapp.eventos.data.repository

import com.tuapp.eventos.di.SupabaseModule
import com.tuapp.eventos.domain.model.Event
import com.tuapp.eventos.domain.model.EventMember
import com.tuapp.eventos.domain.model.EventRoleMember
import com.tuapp.eventos.domain.model.Expense
import com.tuapp.eventos.domain.model.Role
import com.tuapp.eventos.domain.model.GroupMember
import com.tuapp.eventos.domain.model.MemberRole
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Columns
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

class EventRepositoryImpl : EventRepository {
    
    private val client = SupabaseModule.client

    override fun getEvents(): Flow<List<Event>> = flow {
        try {
            val response = client.from("events")
                .select(Columns.raw("*, groups(name)"))
            
            val jsonElement = Json.parseToJsonElement(response.data)
            if (jsonElement !is kotlinx.serialization.json.JsonArray) {
                emit(emptyList())
                return@flow
            }

            val events = jsonElement.mapNotNull { element ->
                try {
                    val obj = element.jsonObject
                    val eventJson = JsonObject(obj.filterKeys { it != "groups" })
                    val event = Json.decodeFromJsonElement(Event.serializer(), eventJson)
                    
                    val groupsElement = obj["groups"]
                    val groupName = when (groupsElement) {
                        is kotlinx.serialization.json.JsonObject -> groupsElement["name"]?.jsonPrimitive?.contentOrNull
                        is kotlinx.serialization.json.JsonArray -> if (groupsElement.isNotEmpty()) groupsElement[0].jsonObject["name"]?.jsonPrimitive?.contentOrNull else null
                        else -> null
                    }
                    
                    event.copy(groupName = groupName)
                } catch (e: Exception) {
                    android.util.Log.e("EventRepository", "Error parsing event row: ${e.message}")
                    null
                }
            }
            emit(events)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching events: ${e.message}")
            emit(emptyList())
        }
    }

    override suspend fun getEventById(id: String): Event? {
        return try {
            val response = client.from("events")
                .select(Columns.raw("*, groups(name)")) {
                    filter {
                        eq("id", id)
                    }
                }
            
            val jsonElement = Json.parseToJsonElement(response.data)
            if (jsonElement is kotlinx.serialization.json.JsonArray && jsonElement.isNotEmpty()) {
                val obj = jsonElement[0].jsonObject
                val eventJson = JsonObject(obj.filterKeys { it != "groups" })
                val event = Json.decodeFromJsonElement(Event.serializer(), eventJson)
                
                val groupsElement = obj["groups"]
                val groupName = when (groupsElement) {
                    is kotlinx.serialization.json.JsonObject -> groupsElement["name"]?.jsonPrimitive?.contentOrNull
                    is kotlinx.serialization.json.JsonArray -> if (groupsElement.isNotEmpty()) groupsElement[0].jsonObject["name"]?.jsonPrimitive?.contentOrNull else null
                    else -> null
                }
                
                event.copy(groupName = groupName)
            } else {
                null
            }
        } catch (e: Exception) {
            null
        }
    }

    override suspend fun createEvent(event: Event, roles: List<Role>): Result<String> {
        return try {
            android.util.Log.d("EventRepository", "Creating event: $event")
            
            // Convert to JSON and remove fields that should be generated by DB
            val eventJson = Json.encodeToJsonElement(Event.serializer(), event).jsonObject.toMutableMap()
            eventJson.remove("id")
            eventJson.remove("created_at")
            eventJson.remove("updated_at")
            
            // Filter out any remaining nulls to avoid constraint violations
            val filteredJson = eventJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
            
            val insertedEvent = client.from("events")
                .insert(filteredJson) {
                    select()
                }
                .decodeSingle<Event>()
            
            val eventId = insertedEvent.id ?: throw Exception("Failed to get event ID")

            if (roles.isNotEmpty()) {
                val rolesToInsert = roles.map { role ->
                    val roleJson = Json.encodeToJsonElement(Role.serializer(), role.copy(eventId = eventId)).jsonObject.toMutableMap()
                    roleJson.remove("id")
                    roleJson.remove("created_at")
                    roleJson.filterValues { it !is kotlinx.serialization.json.JsonNull }
                }
                client.from("event_roles").insert(rolesToInsert)
            }

            val ownerMember = EventMember(
                eventId = eventId,
                userId = event.createdBy,
                isAdmin = true,
                status = "active"
            )
            
            // Clean member JSON as well
            val ownerJson = Json.encodeToJsonElement(EventMember.serializer(), ownerMember).jsonObject.toMutableMap()
            ownerJson.remove("joined_at")
            ownerJson.remove("created_at")
            
            client.from("event_members").insert(ownerJson.filterValues { it !is kotlinx.serialization.json.JsonNull })

            Result.success(eventId)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error creating event: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun updateEvent(event: Event): Result<Unit> {
        return try {
            client.from("events").update(event) {
                filter {
                    eq("id", event.id ?: "")
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error updating event: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun joinEvent(eventId: String, userId: String): Result<Unit> {
        return try {
            android.util.Log.d("EventRepository", "Attempting to join event $eventId for user $userId")
            // First check if already member to avoid duplicate key error
            val existing = client.from("event_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                        eq("user_id", userId)
                    }
                }.decodeSingleOrNull<EventMember>()

            if (existing != null) {
                android.util.Log.d("EventRepository", "User already joined event")
                return Result.success(Unit)
            }

            val member = EventMember(
                eventId = eventId,
                userId = userId,
                isAdmin = false,
                status = "active"
            )
            
            // Clean member JSON to avoid null date constraint errors
            val memberJson = Json.encodeToJsonElement(EventMember.serializer(), member).jsonObject.toMutableMap()
            memberJson.remove("joined_at")
            memberJson.remove("created_at")
            
            client.from("event_members").insert(memberJson.filterValues { it !is kotlinx.serialization.json.JsonNull })

            android.util.Log.d("EventRepository", "Successfully joined event")
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error joining event: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun leaveEvent(eventId: String, userId: String): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            android.util.Log.d("EventRepository", "Removing user $userId from event $eventId")
            
            // 1. Eliminar al usuario de todos los roles que tenga asignados en este evento
            client.from("event_role_members").delete {
                filter {
                    eq("event_id", eventId)
                    eq("user_id", userId)
                }
            }
            
            // 2. Eliminar al usuario de la tabla de miembros del evento
            client.from("event_members").delete {
                filter {
                    eq("event_id", eventId)
                    eq("user_id", userId)
                }
            }
            
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error removing user from event: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun getParticipatingEventIds(userId: String): Result<List<String>> {
        return try {
            val members = client.from("event_members")
                .select {
                    filter {
                        eq("user_id", userId)
                    }
                }
                .decodeList<EventMember>()
            Result.success(members.map { it.eventId })
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun isUserParticipating(eventId: String, userId: String): Result<Boolean> {
        return try {
            val member = client.from("event_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                        eq("user_id", userId)
                    }
                }
                .decodeSingleOrNull<EventMember>()
            Result.success(member != null)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getEventParticipants(eventId: String): Result<List<GroupMember>> {
        return try {
            val response = client.from("event_members")
                .select(Columns.raw("*, profiles(*)")) {
                    filter {
                        eq("event_id", eventId)
                    }
                }
            
            val jsonElement = Json.parseToJsonElement(response.data)
            if (jsonElement !is kotlinx.serialization.json.JsonArray) {
                return Result.success(emptyList())
            }
            
            val participants = jsonElement.mapNotNull { element ->
                try {
                    val obj = element.jsonObject
                    val userId = obj["user_id"]?.jsonPrimitive?.contentOrNull ?: return@mapNotNull null
                    val isAdmin = obj["is_admin"]?.jsonPrimitive?.let { 
                        it.booleanOrNull ?: (it.content == "true") || (it.content == "1")
                    } ?: false
                    
                    // Manejar que profiles pueda venir como objeto o como lista (Join 1:1 vs 1:N)
                    val profilesElement = obj["profiles"]
                    val profileObj = when (profilesElement) {
                        is kotlinx.serialization.json.JsonObject -> profilesElement
                        is kotlinx.serialization.json.JsonArray -> if (profilesElement.isNotEmpty()) profilesElement[0].jsonObject else null
                        else -> null
                    }
                    
                    val fullName = profileObj?.get("full_name")?.jsonPrimitive?.contentOrNull ?: "Usuario"
                    val username = profileObj?.get("username")?.jsonPrimitive?.contentOrNull ?: "usuario"
                    
                    GroupMember(
                        userId = userId,
                        userName = fullName,
                        role = if (isAdmin) MemberRole.ADMIN else MemberRole.MEMBER,
                        email = "@$username"
                    )
                } catch (e: Exception) {
                    android.util.Log.e("EventRepository", "Error parsing participant row: ${e.message}")
                    null
                }
            }
            
            Result.success(participants)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error getting participants: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun updateParticipantRole(eventId: String, userId: String, isAdmin: Boolean): Result<Unit> {
        return try {
            android.util.Log.d("EventRepository", "Updating role: event=$eventId, user=$userId, isAdmin=$isAdmin")
            
            // Usamos update en lugar de upsert para evitar activar múltiples políticas (INSERT y UPDATE)
            // y para que sea más eficiente cuando ya sabemos que el registro existe.
            client.from("event_members").update(
                buildJsonObject {
                    put("is_admin", isAdmin)
                }
            ) {
                filter {
                    eq("event_id", eventId)
                    eq("user_id", userId)
                }
            }
            
            android.util.Log.d("EventRepository", "Update successful")
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error updating participant role for user $userId in event $eventId: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun getRoles(eventId: String): Result<List<Role>> {
        return try {
            val roles = client.from("event_roles")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<Role>()
            Result.success(roles)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun createRole(role: Role): Result<Unit> {
        return try {
            val jsonConfig = Json { encodeDefaults = false; ignoreUnknownKeys = true }
            val roleJson = jsonConfig.encodeToJsonElement(Role.serializer(), role).jsonObject.toMutableMap()
            roleJson.remove("id")
            roleJson.remove("created_at")
            
            val finalJson = JsonObject(roleJson)
            android.util.Log.d("EventRepository", "Inserting role: $finalJson")
            
            client.from("event_roles").insert(finalJson)
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error creating role: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun updateRole(role: Role): Result<Unit> {
        return try {
            val jsonConfig = Json { encodeDefaults = false; ignoreUnknownKeys = true }
            val roleJson = jsonConfig.encodeToJsonElement(Role.serializer(), role).jsonObject.toMutableMap()
            
            // Limpieza crucial para evitar errores de restricción en la DB
            roleJson.remove("created_at")
            
            val finalJson = JsonObject(roleJson)
            android.util.Log.d("EventRepository", "Updating role: $finalJson")

            client.from("event_roles").update(finalJson) {
                filter {
                    eq("id", role.id ?: "")
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error updating role: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun deleteRole(roleId: String): Result<Unit> {
        return try {
            client.from("event_roles").delete {
                filter {
                    eq("id", roleId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun assignRoleToUser(roleId: String, userId: String, eventId: String): Result<Unit> {
        return try {
            // Check if user is participating in the event first
            val isParticipating = isUserParticipating(eventId, userId).getOrDefault(false)
            if (!isParticipating) {
                return Result.failure(Exception("Debes unirte al evento antes de asignarte un rol"))
            }

            val roleMember = EventRoleMember(
                roleId = roleId,
                userId = userId,
                eventId = eventId
            )
            client.from("event_role_members").insert(roleMember)
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error assigning role: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun removeRoleFromUser(roleId: String, userId: String): Result<Unit> {
        return try {
            client.from("event_role_members").delete {
                filter {
                    eq("role_id", roleId)
                    eq("user_id", userId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getRoleMembers(eventId: String): Result<List<EventRoleMember>> {
        return try {
            val members = client.from("event_role_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<EventRoleMember>()
            Result.success(members)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun updateEventStatus(eventId: String, status: String): Result<Unit> {
        return try {
            val data = buildJsonObject {
                put("status", status)
            }
            client.from("events").update(data) {
                filter { eq("id", eventId) }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun assignMultipleRoles(assignments: List<EventRoleMember>): Result<Unit> {
        return try {
            client.from("event_role_members").insert(assignments)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteEvent(eventId: String): Result<Unit> {
        return try {
            client.from("events").delete {
                filter {
                    eq("id", eventId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error deleting event: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun addExpense(eventId: String, expense: Expense): Result<Unit> {
        return try {
            android.util.Log.d("EventRepository", "Preparing to save expense: ${expense.title}")
            
            val jsonConfig = Json { 
                encodeDefaults = false 
                ignoreUnknownKeys = true
            }
            
            val expenseJson = jsonConfig.encodeToJsonElement(Expense.serializer(), expense).jsonObject.toMutableMap()
            
            // Limpieza de campos que genera la BD automáticamente
            expenseJson.remove("id")
            expenseJson.remove("created_at")
            
            // Si la fecha es nula, la BD usará CURRENT_DATE por defecto
            if (expense.incurredAt == null) {
                expenseJson.remove("incurred_at")
            }
            
            val finalJsonObject = JsonObject(expenseJson)
            client.from("expenses").insert(finalJsonObject)
            
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Failed to add expense: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun updateExpense(expense: Expense): Result<Unit> {
        return try {
            val expenseId = expense.id ?: return Result.failure(Exception("Expense ID is required for update"))
            
            val jsonConfig = Json { 
                encodeDefaults = false 
                ignoreUnknownKeys = true
            }
            
            val expenseJson = jsonConfig.encodeToJsonElement(Expense.serializer(), expense).jsonObject.toMutableMap()
            
            // No actualizamos el ID ni la fecha de creación
            expenseJson.remove("id")
            expenseJson.remove("created_at")
            
            val finalJsonObject = JsonObject(expenseJson)
            client.from("expenses").update(finalJsonObject) {
                filter {
                    eq("id", expenseId)
                }
            }
            
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Failed to update expense: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun deleteExpense(expenseId: String): Result<Unit> {
        return try {
            client.from("expenses").delete {
                filter {
                    eq("id", expenseId)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Failed to delete expense: ${e.message}", e)
            Result.failure(e)
        }
    }

    override suspend fun getExpenses(eventId: String): List<Expense> {
        return try {
            client.from("expenses")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<Expense>()
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching expenses: ${e.message}")
            emptyList()
        }
    }

    override suspend fun getTasks(eventId: String): List<com.tuapp.eventos.domain.model.EventTask> {
        return try {
            client.from("event_tasks")
                .select {
                    filter {
                        eq("event_id", eventId)
                    }
                }
                .decodeList<com.tuapp.eventos.domain.model.EventTask>()
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error fetching tasks: ${e.message}")
            emptyList()
        }
    }

    override suspend fun createTask(task: com.tuapp.eventos.domain.model.EventTask): Result<Unit> {
        return try {
            val jsonConfig = Json { encodeDefaults = false; ignoreUnknownKeys = true }
            val taskJson = jsonConfig.encodeToJsonElement(com.tuapp.eventos.domain.model.EventTask.serializer(), task).jsonObject.toMutableMap()
            taskJson.remove("id")
            taskJson.remove("created_at")
            
            client.from("event_tasks").insert(JsonObject(taskJson))
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun updateTask(task: com.tuapp.eventos.domain.model.EventTask): Result<Unit> {
        return try {
            val taskId = task.id ?: return Result.failure(Exception("Task ID is required"))
            val jsonConfig = Json { encodeDefaults = false; ignoreUnknownKeys = true }
            val taskJson = jsonConfig.encodeToJsonElement(com.tuapp.eventos.domain.model.EventTask.serializer(), task).jsonObject.toMutableMap()
            taskJson.remove("id")
            taskJson.remove("created_at")

            client.from("event_tasks").update(JsonObject(taskJson)) {
                filter { eq("id", taskId) }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteTask(taskId: String): Result<Unit> {
        return try {
            client.from("event_tasks").delete {
                filter { eq("id", taskId) }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun notifyTask(taskId: String, eventId: String, roleId: String, senderId: String, message: String): Result<Unit> {
        return try {
            android.util.Log.d("EventRepository", "Attempting to notify task: taskId=$taskId, roleId=$roleId")
            
            // 1. Obtener usuarios asignados al rol en este evento
            val roleMembers = client.from("event_role_members")
                .select {
                    filter {
                        eq("event_id", eventId)
                        eq("role_id", roleId)
                    }
                }.decodeList<EventRoleMember>()

            if (roleMembers.isEmpty()) {
                android.util.Log.w("EventRepository", "No users assigned to role $roleId")
                return Result.failure(Exception("No hay usuarios asignados a este rol para notificar"))
            }

            // 2. Crear notificaciones para cada usuario
            val notifications = roleMembers.map { member ->
                buildJsonObject {
                    put("task_id", taskId)
                    put("receiver_id", member.userId)
                    put("sender_id", senderId)
                    put("message", message)
                    put("status", "pending")
                }
            }

            client.from("notifications_event_tasks").insert(notifications)
            android.util.Log.d("EventRepository", "Task notifications sent successfully to ${roleMembers.size} users")
            Result.success(Unit)
        } catch (e: Exception) {
            android.util.Log.e("EventRepository", "Error in notifyTask: ${e.message}", e)
            Result.failure(e)
        }
    }

    override fun getEventsByGroup(groupId: String): Flow<List<Event>> = flow {
        try {
            val response = client.from("events")
                .select(Columns.raw("*, groups(name)")) {
                    filter {
                        eq("group_id", groupId)
                    }
                }
            
            val jsonElement = Json.parseToJsonElement(response.data)
            if (jsonElement !is kotlinx.serialization.json.JsonArray) {
                emit(emptyList())
                return@flow
            }

            val events = jsonElement.mapNotNull { element ->
                try {
                    val obj = element.jsonObject
                    val eventJson = JsonObject(obj.filterKeys { it != "groups" })
                    val event = Json.decodeFromJsonElement(Event.serializer(), eventJson)
                    
                    val groupsElement = obj["groups"]
                    val groupName = when (groupsElement) {
                        is kotlinx.serialization.json.JsonObject -> groupsElement["name"]?.jsonPrimitive?.contentOrNull
                        is kotlinx.serialization.json.JsonArray -> if (groupsElement.isNotEmpty()) groupsElement[0].jsonObject["name"]?.jsonPrimitive?.contentOrNull else null
                        else -> null
                    }
                    
                    event.copy(groupName = groupName)
                } catch (e: Exception) {
                    android.util.Log.e("EventRepository", "Error parsing event row: ${e.message}")
                    null
                }
            }
            emit(events)
        } catch (e: Exception) {
            emit(emptyList())
        }
    }

    override suspend fun getExpensesByGroup(groupId: String): Result<List<Expense>> {
        return try {
            android.util.Log.d("EventRepo_FIX", "Loading expenses for group: $groupId")
            // Unimos con la tabla events para filtrar por group_id
            // IMPORTANTE: Para filtrar por una tabla unida, usamos la sintaxis "tabla.columna"
            val response = client.from("expenses")
                .select(Columns.raw("*, events!inner(group_id)")) {
                    filter {
                        // Forzamos el calificador de tabla para evitar el error de columna no encontrada
                        eq("events.group_id", groupId)
                    }
                }
            
            android.util.Log.d("EventRepo_FIX", "Group expenses raw data: ${response.data}")
            
            val jsonElement = Json.parseToJsonElement(response.data)
            if (jsonElement !is kotlinx.serialization.json.JsonArray) {
                return Result.success(emptyList())
            }

            val expenses = jsonElement.map { element ->
                val obj = element.jsonObject.filterKeys { it != "events" }
                Json.decodeFromJsonElement(Expense.serializer(), JsonObject(obj))
            }

            android.util.Log.d("EventRepo_FIX", "Successfully decoded ${expenses.size} expenses")
            Result.success(expenses)
        } catch (e: Exception) {
            android.util.Log.e("EventRepo_FIX", "Error in getExpensesByGroup: ${e.message}", e)
            Result.failure(e)
        }
    }
}
